version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
permissions:
  - object: /var/www/
    owner: root
    group: www-data
    mode: 755
hooks:
  ApplicationStart:
    - location: /startupscript.sh
      timeout: 300
      runas: root
